import { prisma } from "@/lib/prisma";

/**
 * Ключи настроек в `app_settings`. Значения хранятся строками — модель
 * `AppSetting` это просто key-value, без типов.
 */
export const SETTING_KEYS = {
  /** Сайт сам генерирует документы заявки по активным шаблонам CRM. */
  autoGenerateDocuments: "autoGenerateDocuments",
  /** Сайт сам заводит подписанта-водителя у документов заявки. */
  autoSignDocuments: "autoSignDocuments",
} as const;

/**
 * Читает булеву настройку. Отсутствующий ключ — это «ещё не настраивали»,
 * поэтому по умолчанию обе автоматизации выключены: они пишут в CRM, и
 * включать их молча при обновлении нельзя.
 */
export async function getBoolSetting(
  key: string,
  fallback = false
): Promise<boolean> {
  const row = await prisma.appSetting.findUnique({ where: { key } });
  if (!row) return fallback;
  return row.value === "true";
}
