import { getBoolSetting, SETTING_KEYS } from "@/lib/settings";
import IntegrationSettings from "@/components/admin/settings/IntegrationSettings";

export default async function AdminSettingsPage() {
  const [autoGenerateDocuments, autoSignDocuments] = await Promise.all([
    getBoolSetting(SETTING_KEYS.autoGenerateDocuments),
    getBoolSetting(SETTING_KEYS.autoSignDocuments),
  ]);

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">Настройки</h1>
        <p className="mt-1 text-sm text-gray-500">
          Автоматизации интеграции с Yume CRM
        </p>
      </div>

      <IntegrationSettings
        autoGenerateDocuments={autoGenerateDocuments}
        autoSignDocuments={autoSignDocuments}
      />
    </div>
  );
}
