import { prisma } from "@/lib/prisma";
import { yumeApi } from "./api";
import { mapCrmStatus } from "./booking-status";
import { mapDocument, missingTemplates } from "./document-signs";
import type { MappedDocument } from "./document-signs";
import { normalizePhone } from "@/lib/phone";
import { getBoolSetting, SETTING_KEYS } from "@/lib/settings";

// Номер приходит из CRM в произвольном формате и правим мы его best-effort:
// синк не должен падать из-за чужих данных, поэтому неразобранный номер
// сохраняется как есть.
function bestEffortPhone(raw: string | null | undefined): string {
  if (!raw) return "";
  const result = normalizePhone(raw, { resident: true });
  return result.ok ? result.phone : raw;
}

/** Не даём одной заявке ходить в CRM за документами чаще, чем раз в минуту. */
const DOCUMENTS_SYNC_INTERVAL_MS = 60_000;

/**
 * Атомарно занимает заявку под работу с документами.
 *
 * `updateMany` с условием по `documentsSyncedAt` — одна операция Postgres,
 * поэтому из двух параллельных синков ровно один получит `count === 1`.
 * Второй вернёт 0 и в CRM не полезет.
 *
 * Заявки, которой ещё нет в локальной БД, это не касается: документы для неё
 * подтянутся на следующем проходе, когда бронь уже создана.
 */
async function claimDocumentsSync(requestId: number): Promise<boolean> {
  const staleBefore = new Date(Date.now() - DOCUMENTS_SYNC_INTERVAL_MS);
  const claimed = await prisma.booking.updateMany({
    where: {
      requestId,
      OR: [
        { documentsSyncedAt: null },
        { documentsSyncedAt: { lt: staleBefore } },
      ],
    },
    data: { documentsSyncedAt: new Date() },
  });
  return claimed.count > 0;
}

/**
 * Догоняет документы заявки в CRM: генерирует недостающие по активным шаблонам
 * и заводит подписанта-водителя. Возвращает обновлённый список документов для
 * записи в бронь либо null, если делать было нечего.
 *
 * Обе операции пишут в CRM, поэтому вызываются только под захватом заявки —
 * иначе два параллельных синка создают два комплекта документов.
 */
async function ensureRequestDocuments(
  requestId: number,
  clientId: number,
  opts: { autoGenerate: boolean; autoSign: boolean }
): Promise<MappedDocument[] | null> {
  if (!(await claimDocumentsSync(requestId))) {
    console.log(
      `[SyncBookings] CRM #${requestId}: документы уже синхронизирует другой запрос, пропуск`
    );
    return null;
  }

  try {
    const docs = await yumeApi.getRequestDocuments(requestId);
    let changed = false;

    if (opts.autoGenerate) {
      const templates = await yumeApi.getDocumentTemplates();
      for (const tpl of missingTemplates(docs, templates)) {
        const created = await yumeApi.createDocument(requestId, tpl.id);
        docs.push(created);
        changed = true;
        console.log(
          `[SyncBookings] CRM #${requestId}: сгенерирован документ #${created.id} по шаблону «${tpl.name}»`
        );
      }
    }

    // CRM создаёт документ, но подписанта-клиента у него может не быть — тогда
    // водителю нечего подписывать, а ссылка ведёт на голый документ.
    if (opts.autoSign) {
      for (const doc of docs) {
        if (doc.signs.some((s) => s.signer?.type === "client")) continue;
        try {
          const sign = await yumeApi.createDocumentClientSign(doc.id, clientId);
          doc.signs.push(sign);
          changed = true;
          console.log(
            `[SyncBookings] doc #${doc.id}: заведён подписант-клиент ${sign.uuid}`
          );
        } catch (err) {
          // Не роняем синк из-за одного документа — остальные обработаются.
          console.error(
            `[SyncBookings] doc #${doc.id}: не удалось завести подписанта —`,
            err
          );
        }
      }
    }

    return changed ? docs.map(mapDocument) : null;
  } catch (err) {
    console.error(
      `[SyncBookings] CRM #${requestId}: не удалось догнать документы —`,
      err
    );
    return null;
  }
}

export async function syncUserBookings(userId: string): Promise<number> {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true, clientId: true },
  });

  if (!user?.clientId) {
    console.log(`[SyncBookings] user ${userId}: no clientId, skipping`);
    return 0;
  }

  const requests = await yumeApi.getAllClientRequests(user.clientId);
  console.log(
    `[SyncBookings] clientId=${user.clientId}: fetched ${requests.length} CRM requests`
  );

  // Читаем один раз на весь проход: настройки не меняются в середине синка.
  const [autoGenerate, autoSign] = await Promise.all([
    getBoolSetting(SETTING_KEYS.autoGenerateDocuments),
    getBoolSetting(SETTING_KEYS.autoSignDocuments),
  ]);

  let synced = 0;
  let skippedNoInv = 0;
  let skippedNoCar = 0;
  for (const req of requests) {
    const firstInv = req.inventories[0];
    if (!firstInv) {
      skippedNoInv++;
      console.log(
        `[SyncBookings] CRM #${req.id} (status=${req.status}): no inventories attached, skipping`
      );
      continue;
    }

    const car = await prisma.car.findUnique({
      where: { inventoryId: firstInv.inventory },
    });
    if (!car) {
      skippedNoCar++;
      console.log(
        `[SyncBookings] CRM #${req.id}: car inventoryId=${firstInv.inventory} (${firstInv.inventory_name} ${firstInv.inventory_car_number}) not in local DB, skipping`
      );
      continue;
    }

    const existing = await prisma.booking.findUnique({
      where: { requestId: req.id },
    });

    // Неизвестный статус оставляет заявку как есть; PENDING — только для новых.
    const status = mapCrmStatus(req.status, existing?.status ?? "PENDING");

    // Fetch documents for confirmed/active bookings. Здесь только чтение —
    // всё, что пишет в CRM, идёт после upsert, под захватом заявки.
    const needsDocuments = ["CONFIRMED", "ACTIVE"].includes(status);
    let documents: unknown | undefined;
    if (needsDocuments) {
      try {
        const docs = await yumeApi.getRequestDocuments(req.id);
        console.log(`[SyncBookings] CRM #${req.id}: ${docs.length} docs fetched`);
        documents = docs.map(mapDocument);
      } catch {
        // CRM unavailable — keep existing
      }
    }

    // Don't overwrite locally cancelled bookings until CRM catches up
    if (existing?.status === "CANCELLED" && status !== "CANCELLED") {
      continue;
    }

    // Local RETURN_PENDING always waits for explicit manager approval in CRM
    // (inventorization.checked = true). Do NOT fall through to the upsert below
    // even if CRM status reports "completed" — manager may still reject the return.
    // Local RETURN_PENDING waits for CRM request to transition to "completed"
    // (manager finalises the rental in Yume after reviewing return photos).
    // Yume auto-sets inventorization.checked=true on API-created records, so
    // it cannot be used as an approval signal — we track request.status.
    if (existing?.status === "RETURN_PENDING") {
      if (status === "COMPLETED") {
        await prisma.booking.update({
          where: { id: existing.id },
          data: { status: "COMPLETED" },
        });
        synced++;
        console.log(
          `[SyncBookings] CRM #${req.id}: crmStatus=${req.status} → COMPLETED`
        );
      } else {
        console.log(
          `[SyncBookings] CRM #${req.id}: RETURN_PENDING held (crmStatus=${req.status})`
        );
      }
      continue;
    }

    // Fetch cancellation reason only on transition to CANCELLED (or first sync of an already-cancelled request)
    const becameCancelled =
      status === "CANCELLED" && existing?.status !== "CANCELLED";
    if (becameCancelled) {
      try {
        const [comments, serviceUserId] = await Promise.all([
          yumeApi.getRequestComments(req.id),
          yumeApi.getServiceUserId(),
        ]);
        const latest = comments
          .filter((c) => c.body && c.user !== serviceUserId)
          .sort(
            (a, b) =>
              new Date(b.created_at).getTime() -
              new Date(a.created_at).getTime()
          )[0];
        if (latest?.body) {
          await prisma.booking.updateMany({
            where: { requestId: req.id },
            data: { cancellationReason: latest.body },
          });
        }
      } catch {
        // CRM unavailable
      }
    }

    await prisma.booking.upsert({
      where: { requestId: req.id },
      update: {
        startDate: new Date(req.rent_start),
        endDate: new Date(req.rent_end),
        totalPrice: Math.round(parseFloat(req.price)),
        status,
        ...(documents !== undefined && { documents }),
      },
      create: {
        requestId: req.id,
        userId: user.id,
        carId: car.id,
        startDate: new Date(req.rent_start),
        endDate: new Date(req.rent_end),
        totalPrice: Math.round(parseFloat(req.price)),
        discountPercent:
          req.price !== req.price_discount
            ? Math.round(
                (1 - parseFloat(req.price_discount) / parseFloat(req.price)) * 100
              )
            : 0,
        status,
        customerName: req.client.name,
        customerPhone: bestEffortPhone(req.client.phone),
        ...(documents && { documents }),
      },
    });
    synced++;

    // Запись в CRM — только после upsert: до него брони может не быть в БД,
    // и захватывать было бы нечего.
    if (needsDocuments && (autoGenerate || autoSign)) {
      const refreshed = await ensureRequestDocuments(req.id, user.clientId, {
        autoGenerate,
        autoSign,
      });
      if (refreshed) {
        await prisma.booking.updateMany({
          where: { requestId: req.id },
          data: { documents: refreshed },
        });
      }
    }
  }

  console.log(
    `[SyncBookings] clientId=${user.clientId}: synced=${synced}, skippedNoInv=${skippedNoInv}, skippedNoCar=${skippedNoCar}`
  );
  return synced;
}
