"use client";

import { useState } from "react";

type Props = {
  autoGenerateDocuments: boolean;
  autoSignDocuments: boolean;
};

type Toggle = {
  key: keyof Props;
  title: string;
  description: string;
  warning?: string;
};

const TOGGLES: Toggle[] = [
  {
    key: "autoGenerateDocuments",
    title: "Автогенерация документов",
    description:
      "При синхронизации подтверждённой заявки сайт создаёт недостающие документы по активным шаблонам CRM (договор, акт, путевой лист и т.д.).",
    warning: "Документы создаются в CRM — по одному на каждый активный шаблон.",
  },
  {
    key: "autoSignDocuments",
    title: "Автоподписание",
    description:
      "Сайт заводит подписанта-водителя у документов заявки, чтобы в приложении появилась персональная ссылка на подпись.",
    warning: "Без этого водитель видит документ, но подписать его не может.",
  },
];

export default function IntegrationSettings(initial: Props) {
  const [values, setValues] = useState<Props>(initial);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState("");

  async function save() {
    setSaving(true);
    setError("");
    setSaved(false);
    try {
      const res = await fetch("/api/admin/settings", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          settings: Object.entries(values).map(([key, value]) => ({
            key,
            value: String(value),
          })),
        }),
      });
      if (!res.ok) {
        setError("Не удалось сохранить настройки");
        return;
      }
      setSaved(true);
    } catch {
      setError("Не удалось сохранить настройки");
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="rounded-xl bg-white p-6 shadow-sm">
      <h2 className="mb-1 text-lg font-semibold text-gray-900">
        Документы и подписание
      </h2>
      <p className="mb-6 text-sm text-gray-500">
        Обе автоматизации пишут в Yume CRM. По умолчанию выключены.
      </p>

      <div className="space-y-4">
        {TOGGLES.map((t) => (
          <label
            key={t.key}
            className="flex cursor-pointer items-start gap-3 rounded-lg border border-gray-200 p-4 transition-colors hover:border-cyan-300"
          >
            <input
              type="checkbox"
              checked={values[t.key]}
              onChange={(e) => {
                setValues((p) => ({ ...p, [t.key]: e.target.checked }));
                setSaved(false);
              }}
              className="mt-0.5 h-5 w-5 rounded border-gray-300 text-cyan-600 focus:ring-cyan-500"
            />
            <span>
              <span className="block font-medium text-gray-900">{t.title}</span>
              <span className="mt-0.5 block text-sm text-gray-600">
                {t.description}
              </span>
              {t.warning && (
                <span className="mt-1 block text-xs text-amber-600">
                  {t.warning}
                </span>
              )}
            </span>
          </label>
        ))}
      </div>

      <div className="mt-6 flex items-center gap-3">
        <button
          onClick={save}
          disabled={saving}
          className="rounded-lg bg-cyan-500 px-5 py-2.5 font-medium text-white transition-colors hover:bg-cyan-600 disabled:opacity-50"
        >
          {saving ? "Сохранение..." : "Сохранить"}
        </button>
        {saved && <span className="text-sm text-green-600">Сохранено</span>}
        {error && <span className="text-sm text-red-600">{error}</span>}
      </div>
    </div>
  );
}
